baseURL = "https://fidelitybookkeepingsolutions.com"
languageCode = "en-us"
title = "Fidelity Bookkeeping Solutions"
copyright = "Copyright &copy; {year} Fidelity Bookkeeping Solutions."
permalinks = "/:slug/"

[params.copyright]
prefix = ""
holder = "Fidelity Bookkeeping Solutions"
startYear = "2020"
suffix = ""

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

# [[menu.main]]
# name = "Home"
# weight = 1
# identifier = "Home"
# url = "/"

[[menu.main]]
name = "Services"
weight = 2
identifier = "Services"
url = "#"

[[menu.main]]
name = "Full-Charge Bookkeeping"
weight = 5
parent = "Services"
identifier = "Full-Charge Bookkeeping"
url = "full-charge-bookkeeping"

[[menu.main]]
name = "Auditing Assistance"
weight = 6
parent = "Services"
identifier = "Auditing Assistance"
url = "auditing-assistance"

[[menu.main]]
name = "Accounting & Analytics"
weight = 7
parent = "Services"
identifier = "Accounting & Analytics"
url = "accounting-analytics"

[[menu.main]]
name = "Policy & Procedure Development"
weight = 7
parent = "Services"
identifier = "Policy & Procedure Development"
url = "policy-procedure-development"

[[menu.main]]
name = "Consulting Services"
weight = 8
parent = "Services"
identifier = "Consulting Services"
url = "consulting-services"

[[menu.main]]
name = "About Us"
weight = 1
identifier = "About Us"
url = "about-us"

# [[menu.main]]
# name = "Contact us"
# weight = 4
# identifier = "Contact Us"
# url = "contact-us"